udistrital/planeacion_cliente

angular.json
fix: ajustes para solución en compilación cliente
=> fix: ajustes para solución en compilación cliente

src/environments/environment.test.ts
management: Ajuste del token de autenticación en ambiente de test y url de redirección
=> management: Ajuste del token de autenticación en ambiente de test y url de redirección

src/environments/environment.test.ts
hotfix:ajuste de variable en test
=> hotfix:ajuste de variable en test

src/environments/environment.test.ts
hotfix:Ajuste de variable de entorno por autenticación para el mid
=> hotfix:Ajuste de variable de entorno por autenticación para el mid

src/app/pages/plan/arbol/arbol.component.html, src/app/pages/plan/arbol/arbol.component.scss, src/app/pages/plan/arbol/arbol.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.html, src/app/pages/plan/listar-plan/listar-plan.component.scss, src/app/pages/plan/listar-plan/listar-plan.component.ts, src/environments/environment.test.ts
management: ajustes en la funcionalidad para inactivar hijos o planes
=> management: ajustes en la funcionalidad para inactivar hijos o planes 

package-lock.json, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.html, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.scss, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts
feat:Ajuste parámetros tipo de dato y requerido
=> feat:Ajuste parametros tipo de dato y requerido

src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.html, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.scss, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts
fix:Ajuste error dialog_editar en componente de construcción
=> fix:Ajuste error dialog_editar en componente de construccion

src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.html, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.html, src/app/pages/plan/crear-plan/crear-plan.component.scss, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.ts
fix: Ajustes funciones de componente construcción
=> fix: Ajustes funciones de componente construccion

src/app/pages/plan/crear-plan/crear-plan.component.html
fix: Ajuste mat-card para formato
=> fix: Ajuste mat-card para formato

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
feat: se consumen servicios de oikos y parametros para vigencias y unidades. Característica #59
=> feat: se consumen servicios de oikos y parametros para vigencias y unidades #59

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.html, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
mangement: se consumen servicios de oikos y parametros para vigencias y unidades
=> mangement: se consumen servicios de oikos y parametros para vigencias y unidades

src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts
fix: requestURL para parametros_crud en autenticación. Característica #59
=> fix: fix: requestURL para parametros_crud en autenticación. Característica #59

src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts
hotfix: Ajuste de variable de entorno de parámetros
=> hotfix: Ajuste de variable de entorno de parametros

src/app/pages/formulacion/formulacion.component.ts
Feat/estado formulado al culminar plan
=> feat: Estado formulado al culminar plan

src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts
management: ajuste de flujo y boton culminar plan
=> management: ajuste de flujo y boton culminar plan 

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.html, src/app/pages/plan/construir-plan/construir-plan.component.html, src/app/pages/plan/consultar-plan/consultar-plan.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.ts
feat: ajuste flujo para tabla resumen y creación de tabla con columnas dinámica. Característica #67
=> feat:tablaResumen

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.html, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts
feat: flujo y configuración para el select dinámico en el cliente. Característica #73
=> feat: select dinámico cliente

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.ts
feat: Visualización armonización
=> Feat/ Visualización armonización

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.ts
fix: Ajustes visualización armonización
=> fix: Ajustes visualizacion armonizacion

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.ts
hotfix: Ajustes visualización armonización
=> hotfix: Ajustes visualización armonización

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts
feat: se ajustan los flujos de contratistas y se crea la validación de los campos de las tablas. Característica #99
=> feat:bugsIdentificacion

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts, src/app/pages/plan/arbol/arbol.component.ts
hotfix: Ajustes de tablas de identificación plan de acción
=> hotfix: Ajustes de tablas de identificación plan de acción 

src/app/pages/formulacion/formulacion.component.ts
fix: errores bandera en formulación.
=> fix: errores bandera en formulación

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.scss, src/app/pages/formulacion/contratistas/contratistas.component.ts
fix: Ajuste valor unitario tabla contratistas
=> fix: Ajuste valor unitario tabla contratistas

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts
feat: se ajusta el flujo para guardado y consulta de la identificación de recursos y contratistas
=> feat:consumoServiciosTabla

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.scss, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts
management: Desarrollo tablas identificación
=> management: Desarrollo tablas identificación 

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.scss, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.spec.ts, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.scss, src/app/pages/pages.module.ts, src/environments/environment.ts
feat: creación y ajustes del componente de identificación de recursos docente. Característica #103
=> feat:IdentificacionDocente

src/app/pages/formulacion/formulacion.component.html
fix:Ajuste flujo arbol armonizacion
=> fix:Ajuste flujo arbol armonizacion

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.scss, src/app/pages/formulacion/formulacion.component.ts
feat: visualización de estado del plan y versión del plan. #125
=> feat: estado-version

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.html, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/main.ts
fix: Ajuste de errores encontrados en pruebas
resolves #112
=> fix: Ajuste de errores encontrados en pruebas

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.scss
fix: Ajustes visuales para la formulación de planes
=> fix: Ajustes visuales para la formulacion de planes

src/app/pages/formulacion/formulacion.component.html
fix: ajuste de despliegue con cambio de funcionalidad #124
=> fix: ajuste de despliegue con cambio de funcionalidad #124

src/app/pages/formulacion/formulacion.component.ts
fix: ajuste de campo observación según flujo modificado #124
=> fix: ajuste de campo observación según flujo modificado

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts
hotfix: ajuste de campo observación según flujo modificado
=> hotfix: ajuste de campo observación según flujo modificado

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts, src/environments/environment.ts
feat: Flujo de observaciones para las identificaciones
=> feat: Flujo de observaciones para las identificaciones

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts, src/environments/environment.ts
mangement: Flujo de observaciones para las identificaciones
=> mangement: Flujo de observaciones para las identificaciones

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.ts
fix: Ajustes observaciones formulacion
=> fix: Ajustes observaciones formulacion

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts, src/main.ts
feat: Flujo de estados para la formulación y nuevo dashboard
=> feat: Flujo de estados para la formulacion y nuevo dashboard

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts, src/environments/environment.ts, src/main.ts
hotfix: Flujo de estados para la formulacion y nuevo dashboard
=> hotfix: Flujo de estados para la formulacion y nuevo dashboard

src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts
Feat: observaciones docentes
resolve #155
=> Feat: observaciones docentes

src/app/pages/formulacion/formulacion.component.ts
=> fix:Ajuste select de unidades

src/app/app.module.ts, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/environments/environment.ts
fix: Ajuste Tabla Identificacion Docente con Desagregado
=> fix: Ajuste Tabla Identificacion Docente con Desagregado

src/app/pages/pages.module.ts
fix: solución error compilación
=> fix: solución error compilación

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/recursos/recursos.component.html
fix:Ajustes finales para componentes de identificación
=> fix:Ajustes finales para componentes de identificacion

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/pages.module.ts
hotfix:Ajustes finales para componentes de identificacion
=> hotfix:Ajustes finales para componentes de identificacion 

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
fix: Ajustes variables de entorno para desagregado docente
=> fix: Ajustes variables de entorno para desagregado docente

src/app/pages/seguimiento/evidencias/evidencias.component.html, src/app/pages/seguimiento/evidencias/evidencias.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.html, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts, src/assets/json/data-gestion-seg.json
fix:ajuste visualización tablas en seguimiento
=> fix:ajuste visualización tablas en seguimiento

src/app/app.module.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.scss, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.spec.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/environments/environment.ts, src/main.ts
feat: Modulo para la gestión de reportes
=> feat: Modulo para la gestion de reportes

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/pages-routing.module.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.scss, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.scss, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.html, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts, src/environments/environment.ts
feat: Funciones para listado de planes y gestion de seguimiento
=> feat: Funciones para listado de planes y gestion de seguimiento

src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
fix: Ajuste variable de entorno PLANES_MID
=> fix: Ajuste variable de entorno PLANES_MID

src/app/pages/evaluacion/evaluacion.component.ts, src/assets/json/evaluacion.json
feat: ajuste en la suma de los datos totales en evaluacion
=> feat: ajuste en la suma de los datos totales en evaluacion

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts
fix: Ajuste de errores para seguimiento
=> fix: Ajuste de errores para seguimiento

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
fix: Ajustes variables de entorno
=> fix: Ajustes variables de entorno

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
fix: Ajustes variables de entorno gestor documentos
=> fix: Ajustes variables de entorno gestor documentos

src/app/@core/data/menu.service.ts, src/app/app.module.ts, src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.ts, src/app/pages/pages.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts, src/main.ts
fix: Ajustes de identificaciones en formulacion
=> fix: Ajustes de indentificaciones en formulacion

src/app/pages/dashboard/dashboard.component.html, src/app/pages/dashboard/dashboard.component.scss, src/app/pages/formulacion/formulacion.component.html
feat: adicion banner en inicio
=> feat: adicion banner en inicio

src/app/pages/formulacion/formulacion.component.html
fix: ajuste visualización etiqueta "culminar plan"
=> fix: ajuste visualización etiqueta "culminar plan"

src/app/pages/plan/construir-plan/construir-plan.component.ts
fix: Ajuste para construcción de plan
=> fix: Ajuste para construccion de plan

src/app/pages/formulacion/formulacion.component.html, src/app/pages/plan/construir-plan/construir-plan.component.ts
hotfix: Ajuste para construccion de plan #275
=> hotfix: Ajuste para construccion de plan #275

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.ts
fix: ajuste selector evaluacion
=> fix: ajuste selector evaluacion

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts
hotfix: ajuste selector evaluacion #277
=> hotfix: ajuste selector evaluacion #277

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.html, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts
feat: implementacion avance acumulado
=> feat: implementacion avance acumulado

src/app/app.module.ts, src/app/pages/pages.module.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.html, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.scss, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.spec.ts, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.scss, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.html, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.scss, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts, src/main.ts
feat: Modulo seguimiento para planeacion y carga de documentos
=> feat: Modulo seguimiento para planeacion y carga de documentos

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts
fix: Ajustes de variables para componentes de seguimiento
=> fix: Ajustes de variables para componentes de seguimiento

src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts
=> fix: ajuste avance acumulado

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts
hotfix: ajuste avance acumulado
=> hotfix: ajuste avance acumulado

src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts, src/main.ts
fix: Ajuste menú y variables de entorno
=> fix: Ajuste menú y variables de entorno

src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts, src/main.ts
hotfix: Ajuste menú y variables de entorno
=> hotfix: Ajuste menú y variables de entorno

src/environments/environment.prod.ts
hotfix: Ajuste de token id para despliegue inicial en ambiente de test
=> hotfix: Ajuste de token id para despliegue inicial en ambiente de test

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.html, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.scss, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.html, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.scss
feat: Observaciones, estados para seguimiento y ajustes en construcción
=> feat: Observaciones, estados para seguimiento y ajustes en construcción

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.html, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.scss, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.html, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.scss, src/environments/environment.prod.ts
management: Desarrollo modulo segimiento
=> management: Desarrollo modulo segimiento 

src/app/pages/formulacion/formulacion.component.ts
fix: Ajuste variable para peticion  planes_mid
=> fix: Ajuste variable para peticion  planes_mid

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.scss, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.html, src/app/pages/plan/arbol/arbol.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
fix: Ajustes para nueva armonizacion
=> fix: Ajustes para nueva armonizacion

src/app/app.module.ts, src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.scss, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.scss, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.scss, src/app/pages/plan/listar-plan/listar-plan.component.html, src/app/pages/plan/listar-plan/listar-plan.component.scss, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.scss, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
fix: Ajustes visualizacion tablas
=> fix: Ajustes visualizacion tablas

src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/plan/construir-plan-proyecto/construir-plan-proyecto.component.html, src/app/pages/plan/construir-plan-proyecto/construir-plan-proyecto.component.scss, src/app/pages/plan/construir-plan-proyecto/construir-plan-proyecto.component.spec.ts, src/app/pages/plan/construir-plan-proyecto/construir-plan-proyecto.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.html, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/consultar-plan/consultar-plan.component.html, src/app/pages/plan/consultar-plan/consultar-plan.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.html, src/main.ts
reorganización del menú de construcción
=> feat: reorganizacion del menu de construccion

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.scss, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.scss, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.scss, src/app/pages/formulacion/recursos/recursos.component.ts, src/app/pages/plan-indicativo/consultar-pi/consultar-pi.component.scss, src/app/pages/plan/construir-plan-proyecto/construir-plan-proyecto.component.scss, src/app/pages/plan/construir-plan/construir-plan.component.scss, src/app/pages/plan/consultar-plan/consultar-plan.component.scss, src/app/pages/plan/crear-plan/crear-plan.component.scss, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.scss, src/app/pages/plan/listar-plan/listar-plan.component.scss, src/app/pages/seguimiento/evidencias/evidencias.component.scss, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.scss, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.scss, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.scss, wget-log
fix: Ajustes para visualizacion según usuario
=> fix: Ajustes para visualizacion  segun usuario

src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
fix: Ajuste nombre para  variable de entorno
=> fix: Ajuste nombre para  variable de entorno

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.html, src/app/pages/plan/crear-plan/crear-plan.component.scss, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.ts, src/app/pages/pui/pui.component.html, src/app/pages/pui/pui.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
feat: Componentes para crear y visualizar el PUI
=> feat: Componentes para crear y visualizar el PUI

src/app/app.module.ts, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/pages.module.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.scss, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts
fix: Ajustes visuales para identificación docente y administración de fechas
=> fix: Ajustes visuales para identificacion docente y administración de fechas

src/app/pages/formulacion/formulacion.component.ts
fix: Ajuste visualizacion componente de identificación docente
=> fix: Ajuste visualizacion componente de identificacion docente

src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html
fix: Ajuste para carga de identificación docente
=> fix: Ajuste para carga de identificacion docente

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
fix: Ajuste para verificación de sumas
=> fix: Ajuste para verificacion de sumas

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: Ajuste para verificacion de sumas #345
=> hotfix: Ajuste para verificacion de sumas #345

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/construir-plan-proyecto/construir-plan-proyecto.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.ts, src/environments/environment.ts, src/main.ts
fix: Ajustes para modulo de construcción, formulación y observación
=> fix: Ajustes para modulo de construcción, formulación y observación

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/construir-plan-proyecto/construir-plan-proyecto.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.ts, src/environments/environment.ts, src/main.ts
hotfix: Ajustes para modulo de construcción, formulación y observación #355
=> hotfix: Ajustes para modulo de construcción, formulación y observación #355

src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.ts
fix: Ajustes para identificacion docente y de recursos
=> fix: Ajustes para identificacion docente y de recursos

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.html, src/app/pages/plan/arbol/arbol.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.ts
fix: Ajustes para errores encontrados en pruebas
=> fix: Ajustes para errores encontrados en pruebas

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.html, src/app/pages/plan/arbol/arbol.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.ts
hotfix: Ajustes para errores encontrados en pruebas
=> hotfix: Ajustes para errores encontrados en pruebas

src/main.ts
hotfix: se comenta el menu para consumo de servicio de configuraciones
=> hotfix: se comenta el menu para consumo de servicio de configuraciones

src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/main.ts
fix: Ajustes componente de reportes y componente de identificacion docente
=> fix: Ajustes componente de reportes y componente de docentes

src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/main.ts
hotfix: Ajustes componente de reportes y componente de docentes
=> hotfix: Ajustes componente de reportes y componente de docentes

src/app/pages/plan/crear-plan/crear-plan.component.ts
hotfix:Ajuste de id de tipo documento para los PUI
=> hotfix:Ajuste de id de tipo documento para los PUI

src/app/pages/formulacion/docentes/docentes.component.ts
fix: Ajuste carga tabla rubros
=> fix: Ajuste carga tabla rubros

src/app/pages/plan/crear-plan/crear-plan.component.ts
hotfix: Ajuste carga tabla rubros
=> hotfix: Ajuste carga tabla rubros 

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
fix: Ajustes para carga de periodos y rubros
=> fix: Ajustes para carga de periodos y rubros

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
hotfix: Ajustes para carga de periodos y rubros
=> hotfix: Ajustes para carga de periodos y rubros

src/app/pages/formulacion/formulacion.component.ts
fix: Ajuste de bugs ambiente de producción
=> fix: Ajuste de bugs ambiente de produccion

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts
=> fix: Ajustes generales

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
fix: Ajuste definicion de fechas y verificacion de rol
=> fix: Ajuste definicion de fechas y verificacion de rol

src/app/pages/formulacion/formulacion.component.ts
fix: Ajuste de roles para jefe de dependencia
=> fix: Ajuste de roles para jefe de dependencia

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
hotfix: Ajuste de roles para jefe de dependencia
=> hotfix: Ajuste de roles para jefe de dependencia

src/environments/environment.prod.ts
hotfix: ajuste de versión oikos en prod
=> hotfix: ajuste de versión oikos en prod

src/app/pages/formulacion/formulacion.component.ts
This reverts commit 0a5ded0775518c3f7aa20f88ffa6b6eb26cc6c4c.
=> Revert "fix: Ajuste de roles para jefe de dependencia"

src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.scss, src/app/pages/formulacion/recursos/recursos.component.ts, src/environments/environment.ts
fix: Ajustes de bug encontrados durante la prueba piloto
=> fix: Ajustes de bug encontrados durante la prueba piloto

src/app/pages/formulacion/formulacion.component.ts
fix: Ajuste variable de entorno para verificacion de identificaciones
=> fix: Ajuste variable de entorno para verificacion de identificaciones

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.scss, src/app/pages/formulacion/formulacion.component.scss, src/styles.scss
fix: Ajustes visuales para formulacion y arbol
=> fix: Ajustes visuales para formulacion y arbol

src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts
fix: Ajuste rol jefe planeacion para componente de reportes
=> fix: Ajuste rol jefe planeacion para componente de reportes

src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/ped/ped.component.ts, src/app/pages/plan-indicativo/consultar-pi/consultar-pi.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts
fix: Ajustes modulo reportes y eliminacion console.log
=> fix: Ajustes modulo reportes y eliminacion console.log

src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts
fix: Ajuste para guardado de reportes
=> fix: Ajuste para guardado de reportes

src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts
fix: Ajustes componente reportes
=> fix: Ajustes componente reportes

src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html
=> fix: Ajuste tabla reportes

src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts
=> hotfix: Ajuste tabla reportes

src/app/pages/formulacion/contratistas/contratistas.component.ts
fix: Ajuste incremento contratista float
=> fix: Ajuste incremento contratista float

src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html
hotfix: Ajuste incremento contratista float
=> hotfix: Ajuste incremento contratista float

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html
fix: Ajustes visuales componentes de formulacion
=> fix: Ajustes visuales componentes de formulacion

src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html
hotfix: Ajustes visuales componentes de formulacion
=> hotfix: Ajustes visuales componentes de formulacion

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
fix: Ajuste carga data docentes
=> fix: Ajuste carga data docentes

src/app/pages/formulacion/docentes/docentes.component.ts
fix: Ajuste etiqueta identificacion docente
=> fix: Ajuste etiqueta identificacion docente

src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: Ajustes verificación campos docente
=> hotfix: Ajustes verificación campos docente

src/app/pages/formulacion/docentes/docentes.component.ts
fix: Swal para información campos pensiones y cesantías
=> fix: Swal para informacion campos pensiones y cesantias

src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: Swal para informacion campos pensiones y cesantias
=> hotfix: Swal para informacion campos pensiones y cesantias

src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html
hotfix: Ajuste observaciones formulario
=> hotfix: Ajuste observaciones formulario

src/app/pages/formulacion/formulacion.component.html
fix: Ajuste rol para directiva ngIsGranted
=> fix: Ajuste rol para directiva ngIsGranted

src/app/pages/formulacion/formulacion.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts
hotfix: ajsutes de carga de estado formulado en reportes
=> hotfix: ajsutes de carga de estado formulado en reportes

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.ts
- Se añade funcionalidad a módulo formulacion/docentes para manejo de incremento porcentual a salarios.
- Se hace verificación general de totales en pensión y cesantías para que la suma de los aportes coincida con el total por el incremento.
- Dicha verificación informa donde se deben hacer los ajustes manuales de los valores incongruentes.
=> feat: issue #475 Ajuste incremento salarial Docentes

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/recursos/recursos.component.html
management: ajuste para el supuesto en el componente de docente
=> management: ajuste para el supuesto en el componente de docente 

src/app/pages/formulacion/docentes/docentes.component.ts
- Ajuste de suma en pensiones privado y público que verifica con total pensiones.
- Agregado modal cuando no se aplica incremento.
=> fix: issue #475, Ajuste suma pensiones

src/app/pages/formulacion/docentes/docentes.component.ts
Se asegura mediante parentesis que la suma se ejecute bien, pasa que -> (parseFloat() || 0.0) atiende el NaN y lo pasa a cero en dado caso y sin parentesis la operación no era consistente.
=> fix: issue #475, ajuste de parentesis en suma

src/app/pages/formulacion/docentes/docentes.component.ts
mangement: ajustes de suma por paréntesis
=> mangement: ajustes de suma por paréntesis 

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.ts
- Ajuste de cálculo para total salud
- Ajuste de cálculo para total pensión
- Ajuste de cálculo para arl (el método usado queda sujeto a revisión)
- Bandera para espera carga rubros, se tiene en cuenta en el botón guardar, mientras carga el botón está deshabilitado.
=> fix: Ajuste calculo salud - pension - arl

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: Ajuste calculo salud - pension - arl
=> hotfix: Ajuste calculo salud - pension - arl

src/app/pages/formulacion/docentes/docentes.component.ts
- añade filtro a consulta rubros
- ajuste en guardado de rubros
=> fix: añade filtro a consulta de rubros

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
- Se suprime el paginador temporalmente
- Se añade contador de filas
=> fix: ajuste paginador tablas formulacion docentes

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: ajuste paginador tablas formulacion docentes
=> hotfix: ajuste paginador tablas formulacion docentes

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
- Se retorna el paginador pero se limita a mostrar todos los elementos _(sin el paginador no se renderiza el borrado de items)_
- Se ajusta cálculos de caja compesacion y icbf
=> fix: Ajuste de calculo en cajaComp & icbf

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: Ajuste de calculo en cajaComp & icbf
=> hotfix: Ajuste de calculo en cajaComp & icbf

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: ajuste calculo salud a partir de salariobásico
=> hotfix: ajuste calculo salud a partir de salariobásico

src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
hotfix:Ajuste de variable para la generación de reporte general por proxy
=> hotfix:Ajuste de variable para la generación de reporte general por proxy

src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/formulacion/recursos/recursos.component.scss
fix: ajuste de select en recursos para permitir multilinea
=> fix: ajuste de select en recursos para permitir multilinea

src/app/pages/formulacion/formulacion.component.html
=> fix: ajuste para select vació

package-lock.json, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/recursos/recursos.component.ts, src/app/pages/formulacion/recursos/rubros.ts
=> hotfix: Correccion de rubros

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.ts
fix: ajuste de expansión de arboles de armonización
=> fix: ajuste de expansión de arboles de armonización

src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts
hotfix: Cambio de url para reporte general
=> hotfix: Cambio de url para reporte general

src/app/pages/formulacion/formulacion.component.ts
fix: validación de armonización de PI
=> fix: validación de armonización de PI

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts
hotfix: validación de armonización de PI
=> hotfix: validación de armonización de PI 

src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
hotfix: Cambio en consulta de vigencias
=> hotfix: Cambio en consulta de vigencias 

src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
hotfix: Cambio en consulta de vigencias
=> hotfix: Cambio en consulta de vigencias

src/app/pages/formulacion/formulacion.component.ts
feat: Mensaje de error en creación/actualización de actividades
=> feat: Mensaje de error en creación/actualización de actividades

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.scss, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.ts
management: Rubro en identificacion de contratistas al formular un plan
=> management: Rubro en identificacion de contratistas al formular un plan

src/app/pages/formulacion/formulacion.component.ts
feat: cambio de iconos a actividades que no están en formulación
=> feat: cambio de iconos a actividades que no están en formulación

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/contratistas/contratistas.component.scss, src/app/pages/formulacion/formulacion.component.ts
hotfix: Mejora en visualizacion de rubros en contratistas
=> hotfix: Mejora en visualizacion de rubros en contratistas

src/app/pages/formulacion/contratistas/contratistas.component.ts
fix: Mensaje de selección de rubro en contratistas
=> fix: Mensaje de selección de rubro en contratistas

src/app/pages/formulacion/formulacion.component.ts
feat: Mensaje de error en solicitud de ponderación
=> feat: Mensaje de error en solicitud de ponderación

src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/formulacion.component.ts
hotfix: Mensaje de error en solicitud de ponderación
=> hotfix: Mensaje de error en solicitud de ponderación 

src/app/pages/formulacion/formulacion.component.ts
=> feat: Mensaje de error

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/rubros.ts
management: ajustes de visualización de actividades inactivas y iclusión de rubro
=> management: ajustes de visualización de actividades inactivas y iclusión de rubro

src/app/pages/formulacion/recursos/rubros.ts
hotfix:Se incluye el rubro Otros servicios de ensayos y análisis técnicos en la lista
=> hotfix:Se incluye el rubro Otros servicios de ensayos y análisis técnicos en la lista

src/app/pages/formulacion/recursos/rubros.ts
hotfix: Ajustes en modulo de docentes
=> hotfix: Ajustes en modulo de docentes

src/app/pages/formulacion/docentes/docentes.component.ts
feat: ajuste de sueldo básico en rubros #556
=> feat: ajuste de sueldo básico en rubros #556 

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: ajuste de sueldo básico en rubros
=> hotfix: ajuste de sueldo básico en rubros 

src/app/pages/formulacion/formulacion.component.ts
fix: ajuste a mensaje de información contratistas/docentes. #556
=> fix: ajuste a mensaje de información contratistas/docentes. #556

src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.ts
hotfix: ajuste a mensaje de información contratistas/docentes.
=> hotfix: ajuste a mensaje de información contratistas/docentes.

src/app/pages/formulacion/recursos/rubros.ts
hotfix: inclusión de rubros faltantes
=> hotfix: inclusión de rubros faltantes

src/app/pages/formulacion/recursos/rubros.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts
hotfix: ajuste de ingreso de rubro y cambio de variable para reporte individuales por autenticación
=> hotfix: ajuste de ingreso de rubro y cambio de variable para reporte individuales por autenticación

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.ts
fix: ajuste en rol y ponderación
=> fix: ajuste en rol y ponderación

src/app/pages/pages-routing.module.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.scss, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts, src/app/pages/seguimiento/reportar-periodo/reportar-periodo.component.ts
feat: integración de periodo-seguimiento y ajustes en listado de planes de acción en seguimiento. #574
=> feat: integracion de periodo-seguimiento y ajustes en listado de planes de acción en seguimiento. #574

src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.ts
fix: ajuste en calculo de primas para docentes HCP. #556
=> fix: ajuste en calculo de primas para docentes HCP. #556

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.scss, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
feat: cargue de actividad especifica. #575
=> feat: cargue de actividad especifica. #575

src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
fix: ajuste de variables de entorno. #585
=> fix: ajuste de variables de entorno. #585

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
feat: funcionalidad de calculo de componente cuantitativo. #591
=> feat: funcionalidad de calculo de componente cuantitativo. #591

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss
fix: ajustes en archivo css para despliegue. #591
=> fix: ajustes en archivo css para despliegue. #591

src/app/pages/seguimiento/evidencias/evidencias-dialog.component.html, src/app/pages/seguimiento/evidencias/evidencias-dialog.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.scss, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
feat: reporte de actividades y seguimientos. #596
=> feat: reporte de actividades y seguimientos. #596

src/app/pages/seguimiento/evidencias/evidencias-dialog.component.html, src/app/pages/seguimiento/evidencias/evidencias-dialog.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.scss, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
management:  reporte de actividades y seguimientos. #596
=> management:  reporte de actividades y seguimientos. #596

angular.json, src/app/pages/seguimiento/evidencias/evidencias-dialog.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.html, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
feat: Funcionalidad de observaciones de seguimiento. #612
=>  feat: Funcionalidad de observaciones de seguimiento. #612 

src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.scss, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
feat: implementación modulo proyectos inversion
=> feat: implementacion modulo proyectos inversion

src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.scss
fix: se cambia select de unidades por botón y se cambia estilo de la tabla unidades
=> fix: se cambia select de unidades por botón y se cambia estilo de la tabla unidades

src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.scss, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
hotfix: se cambia select de unidades por botón y se cambia estilo de la tabla unidades
=> hotfix: se cambia select de unidades por botón y se cambia estilo de la tabla unidades

src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
Se implementa funcionalidad de guardar para el modulo de inversión y se separan botones de guardar y limpiar de los dos módulos
=> feat: se implementa funcionalidad de guardar para el modulo de inversión y se separan botones de guardar y limpiar de los dos módulos

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
feat: ajustes para modulo de seguimiento plan de acción. #624
=> feat: ajustes para modulo de seguimiento plan de acción. #624

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
Management: ajustes para modulo de seguimiento plan de acción. #624
=> Management: ajustes para modulo de seguimiento plan de acción. #624

src/app/app.module.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.scss, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
"feat: se crea la funcionalidad para la asignación de unidades de interés componente admin #627"
=> feat: se crea la funcionalidad para la asignacion de unidades de interes componente admin #627

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
=> fix: ajustes de tiempo. #638

src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
fix: solución de error de compilación por sintaxis
=> fix: solución de error de compilación por sintaxis

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
fix: ajuste en muestra de loading. #638
=> fix: ajuste en muestra de loading. #638

src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
hotfix: ajuste en muestra de loading. #638
=> hotfix: ajuste en muestra de loading. #638

src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
fix: Correcciones de modulo de seguimiento. #638
=> fix: Correcciones de modulo de seguimiento. #638

src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
hotfix: Correcciones de modulo de seguimiento. #638
=> hotfix: Correcciones de modulo de seguimiento. #638

package-lock.json, package.json, src/app/app.module.ts, src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.scss, src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/pages.module.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
feat: integración de API google chart. #634
=> feat: integración de API google chart. #634

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.scss, src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/seguimiento/evidencias/evidencias-dialog.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.ts
feat: tabla de evaluación planes de acción. #626
=> feat: tabla de evaluación planes de acción. #626

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-fuente-dialog/agregar-fuente-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-fuente/editar-fuente.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-fuente/editar-fuente.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-fuente/editar-fuente.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-fuente/editar-fuente.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/fuentes-de-apropiacion/fuentes-de-apropiacion.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/fuentes-de-apropiacion/fuentes-de-apropiacion.component.ts, src/app/pages/pages.module.ts, src/environments/environment.ts
feat/Se implementa funcionalidad a fuentes de apropiación issue 650
=> feat/Se implementa funcionalidad a fuentes de apropiación issue 650

src/app/pages/formulacion/recursos/rubros.ts
management: inclusición de rubros por ajuste presupuestal vigencia 2023
=> management: inclusición de rubros por ajuste presupuestal vigencia 2023

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-meta-dialog/agregar-meta-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-proyecto-vigente/agregar-proyecto-vigente.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-proyecto-vigente/agregar-proyecto-vigente.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/cargar-soportes-dialog/cargar-soportes-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/cargar-soportes-dialog/cargar-soportes-dialog.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/cargar-soportes-dialog/cargar-soportes-dialog.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-apropiacion-fuente-dialog/editar-apropiacion-fuente-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-apropiacion-fuente-dialog/editar-apropiacion-fuente-dialog.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-apropiacion-fuente-dialog/editar-apropiacion-fuente-dialog.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-apropiacion-fuente-dialog/editar-apropiacion-fuente-dialog.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/fuente-apropiacion-dialog/fuente-apropiacion-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/fuente-apropiacion-dialog/fuente-apropiacion-dialog.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/fuentes-de-apropiacion/fuentes-de-apropiacion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
feat: se implementa consumo del cliente a controlador inversion mid e issue 666
=> feat: se implementa consumo del cliente a controlador inversion mid e issue 666

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-meta-dialog/agregar-meta-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-proyecto-vigente/agregar-proyecto-vigente.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-proyecto-vigente/agregar-proyecto-vigente.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/cargar-soportes-dialog/cargar-soportes-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/cargar-soportes-dialog/cargar-soportes-dialog.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/cargar-soportes-dialog/cargar-soportes-dialog.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-apropiacion-fuente-dialog/editar-apropiacion-fuente-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-apropiacion-fuente-dialog/editar-apropiacion-fuente-dialog.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-apropiacion-fuente-dialog/editar-apropiacion-fuente-dialog.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/editar-apropiacion-fuente-dialog/editar-apropiacion-fuente-dialog.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/fuente-apropiacion-dialog/fuente-apropiacion-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/fuente-apropiacion-dialog/fuente-apropiacion-dialog.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/fuentes-de-apropiacion/fuentes-de-apropiacion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.ts, src/app/pages/formulacion/recursos/rubros.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
management: se implementa consumo del cliente a controlador inversion mid e issue 666
=> management: se implementa consumo del cliente a controlador inversion mid e issue 666

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-proyecto-vigente/agregar-proyecto-vigente.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/cargar-soportes-dialog/cargar-soportes-dialog.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.html
fix: corrección de parametro de consulta en proyectos de inversión vigentes y rutas para controlador de inversión de api mid
=> fix: correccion de parametro de consulta en proyectos de inversion vigentes y rutas para controlador de inversion de api mid

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
feat: Selección rubros de posgrados. #673
=> feat: Selección rubros de posgrados. #673

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.ts
fix: ajuste consumo proyectos de inversion vigentes
=> fix: ajuste consumo proyectos de inversion vigentes

src/app/pages/formulacion/docentes/docentes.component.scss, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.scss, src/app/pages/seguimiento/evidencias/evidencias-dialog.component.html, src/app/pages/seguimiento/evidencias/evidencias-dialog.component.scss, src/app/pages/seguimiento/evidencias/evidencias-dialog.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.scss, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.scss
feat: Ajuste en componente de seguimiento planes de acción #671 y #672
=> feat: Ajuste en componente de seguimiento planes de acción #671 y #672

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html
feat: Ajustes en el calculo de indicadores. #684
=> feat: Ajustes en el calculo de indicadores. #684

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-proyecto-vigente/agregar-proyecto-vigente.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/visualizar-soportes-dialog/visualizar-soportes-dialog.component.scss, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts
feat: se crean nuevos modulos de acuerdo a mockup planes inversión
=> feat: se crean nuevos modulos de acuerdo a mockup planes inversión

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
fix: ajustes en denominador fijo de planes de acción. #696
=> fix: ajustes en denominador fijo de planes de acción. #696

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts
feat: se realizan ajustes con respecto a cambios del mockup
=> feat: se realizan ajustes con respecto a cambios del mockup

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.spec.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
management:  se realizan ajustes con respecto a cambios del mockup
=> management:  se realizan ajustes con respecto a cambios del mockup

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.ts
fix: se realizan ajustes en mockup planes de inversion
=> fix: se realizan ajustes en mockup planes de inversion

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
fix: ajuste en guardado de seguimiento planes de acción
=> fix: ajuste en guardado de seguimiento planes de acción

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-meta-dialog/agregar-meta-dialog.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-proyecto-vigente/agregar-proyecto-vigente.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/cargar-soportes-dialog/cargar-soportes-dialog.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/cargar-soportes-dialog/cargar-soportes-dialog.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
management: Ajustes de error en reportes y en modulo de proyectos de inversión. #705
=> management: Ajustes de error en reportes y en modulo de proyectos de inversión. #705

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.scss
feat: Ajustes visuales al modulo de seguimiento plan de acción
=> feat: Ajustes visuales al modulo de seguimiento plan de acción

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html
fix: ajustes a componente de seguimiento
=> fix: ajustes a componente de seguimiento

src/app/pages/seguimiento/evidencias/evidencias-dialog.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
fix: ajuste de la primera carga del documento
=> fix: ajuste de la primera carga del documento

src/app/app.module.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.ts, src/app/pages/pages-routing.module.ts
feat: se implementan funcionalidades modulo programación de magnitudes y presupuesto
=> feat: se implementan funcionalidades modulo programación de magnitudes y presupuesto

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.ts, src/app/pages/pages-routing.module.ts
fix: se corrigen errores en funcionalidades de formular meta y tabla resumen módulo formulación plan inversión
=> fix: se corrigen errores en funcionalidades de formular meta y tabla resumen módulo formulación plan inversión

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/agregar-meta-dialog/agregar-meta-dialog.component.scss, src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.scss, src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
fix: ajuste en modulo de evaluaciones y reporte 0/0
=> fix: ajuste en modulo de evaluaciones y reporte 0/0

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
fix: ajuste en seguimiento planes de acción
=> fix: ajuste en seguimiento planes de acción

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
fix: ajuste en la carga de documentos planes de acción
=> fix: ajuste en la carga de documentos planes de acción

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
hotfix: ajuste en la carga de documentos planes de acción
=> hotfix: ajuste en la carga de documentos planes de acción

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.ts
fix: se ajusto la representación de los valores mayores a 100 y el alineado en la actividad en el reporte de planes de acción
=> fix: se ajusto la representación de los valores mayores a 100 y el alineado en la actividad en el reporte de planes de acción

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
hotfix: se ajusto la representación de los valores mayores a 100 y el alineado en la actividad en el reporte de planes de acción
=> hotfix: se ajusto la representación de los valores mayores a 100 y el alineado en la actividad en el reporte de planes de acción

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.ts
fix: ajustes modulo de evaluación
=> fix: ajustes modulo de evaluación

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.ts
=> hotfix: ponderado

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.ts
hotfix: ajustes modulo evaluación
=> hotfix: ajustes modulo evaluación

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.ts
fix: se cambia asignación de valor en variable en el componente identificacion-actividades
=> fix: se cambia asignación de valor en variable en el componente identificacion-actividades

src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
fix: ajuste de validación de rol en componente de seguimiento y evaluación
=> fix: ajuste de validación de rol en componente de seguimiento y evaluación

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.scss, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/programacion-presupuestal/programacion-presupuestal.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.html, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/tipo-meta-indicador/tipo-meta-indicador.component.ts
fix: ajustes corrección de bugs
=> fix: ajustes corrección de bugs

src/app/pages/reportes/reporte-plan-anual/plan-anual.component.html, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
fix: ajustes en modulo de reportes y listado de seguimiento de planes de acción
=> fix: ajustes en modulo de reportes y listado de seguimiento de planes de acción

src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
fix: Ajuste en la carga de seguimientos
=> fix: Ajuste en la carga de seguimientos

src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: añadido logica calculos cuando salario minimo bajo (tuleap: 55806)
=> hotfix: añadido logica calculos cuando salario minimo bajo (tuleap: 55806)

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
hotfix: revision ajuste totales salarios totales_individuales
=> hotfix: revision ajuste totales salarios totales_individuales

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/arbol/arbol.component.html, src/app/pages/plan/arbol/arbol.component.scss, src/app/pages/plan/arbol/arbol.component.ts
- https://github.com/udistrital/sga_cliente/issues/1459
=> feat: udistrital/sga_cliente#1459 selección automática elementos árbol según nivel, manejo de no aplica

src/app/@core/utils/gestor_documental.service.ts, src/app/app.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.html, src/app/pages/dashboard/dashboard.component.ts, src/app/pages/pages.component.ts, src/app/pages/pui/pui.component.html, src/app/pages/pui/pui.component.ts, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.html, src/app/pages/seguimiento/generar-trimestre/visualizar-documento-dialog/visualizar-documento-dialog.component.ts, src/app/pages/services/errorManager.ts, src/environments/environment.ts
#809 
#810 
Solución visualización documento, visualización tabla identificación recurso docente, error ortográfico, solución error adición de un subnivel inactivo a un nivel existente y visualización de PUI.
=> fix: solución de hallazgos asignados en issue

package-lock.json, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.html, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts, src/environments/environment.ts
#809 
#810 
Bugs:
- Carga en las fechas para procesos de formulación y seguimiento
- Construcción de un nuevo plan/proyecto al definirlo de tipo Proyecto
- Realizar ajustes a un plan de acción de manera correcta
- Formulario dinámico en la adición y edición de niveles
=> fix: Cambios iniciales (bugs)

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
#810 
#809 
Bugs solucionados:
- Editar plan con éxito en plan/listar-plan, ped/ped y pi/consultar-pi
- Solución de persistencia de datos y errores nulos en proyectos-macro/formular-proyecto
- Solución botón limpiar en plan/habilitar-reporte
=> fix: solución bugs editar plan, datos persistentes y botón limpiar

src/app/pages/formulacion/contratistas/contratistas.component.html, src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.html, src/app/pages/ped/ped.component.ts, src/app/pages/plan-indicativo/consultar-pi/consultar-pi.component.ts, src/app/pages/plan/arbol/arbol.component.html, src/app/pages/plan/arbol/arbol.component.scss, src/app/pages/plan/arbol/arbol.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html
#809 
#810 
Bugs:
- Manejo de error al crear actividad con PED o PI erroneo
- Inhabilitación del desplegable 'rubros', visibilización de botón ymensaje en contratistas, recursos y docentes
- Visualización de planes inactivos, cambio ruta erronea delete y callbacks sin usar en PED y PI
- Cambio de formato en etiqueta para fechas
- Creación y actualización en vista para Plan de Acción Anual
=> fix: bugs felipe

package-lock.json, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/fuentes-de-apropiacion/fuentes-de-apropiacion.component.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/ped/consultar-dialog-ped/consultar-dialog-ped.component.ts, src/app/pages/ped/evaluacion-ped/evaluacion-ped.component.ts, src/app/pages/ped/ped.component.ts, src/app/pages/ped/seguimiento-ped/seguimiento-ped.component.ts, src/app/pages/plan/construir-plan-proyecto/construir-plan-proyecto.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.ts, src/environments/environment.ts
#810 
tiempos de espera en listar-plan y /construir-plan-proyecto.
consultar informacion y eliminar fuente.
=> fix: load de carga front

src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
#809 
#810 
Bug: 
- Corrección en la carga de fechas para procesos de formulación y seguimiento (Se añaden observaciones)
=> fix: Corrección en la carga de fechas para procesos de formulación y seguimiento

src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts, src/app/pages/plan/habilitar-reporte/habilitar-reporte.component.ts
- Se corrigió el error de que al intentar editar un subnivel el botón de guardar estaba inhabilitado, aunque se modificara el formulario.
=> fix: se solucionó el botón de guardar inhabilitado para editar un subnivel en proyecto

src/app/pages/plan/crear-plan/crear-plan.component.html
#809 
#810 
Bug 
- Correción de un bug presentado en la Construcción de un Plan/Proyecto de tipo Proyecto
=> fix: Corrección creación de un nuevo plan/proyecto de tipo plan

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.html, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
#821 
Se implemento el estado de revisión verificada para seguimiento y formulación por parte del rol JEFE_UNIDAD_PLANEACION.
=> feat: flujo de verificación para seguimiento y formulación de parte del rol JEFE_UNIDAD_PLANEACION

src/app/pages/formulacion/docentes/docentes.component.html, src/app/pages/formulacion/docentes/docentes.component.ts
#842 
Consumo de controlador calculos identificación docentes
=> feat: Consumo de controlador calculos identificación docentes

src/app/pages/formulacion/docentes/docentes.component.ts
#884
Pruebas funcionales - componente "Identificación docente"
=> feat: Pruebas funcionales - componente "Identificación docente" 

src/app/pages/formulacion/formulacion.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts
fix: actualización de archivos - desarrollos sprints 1 y 2
=> fix: actualización de archivos - desarrollos sprints 1 y 2

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.scss, src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/formulacion/formulacion.component.ts
issu #859 y #861 y solucion a bug parte 2 #810
=> fead:inclucion de campo brecha en la tabla evaluacion 

src/app/pages/formulacion/formulacion.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts
fix: corrección bug formulación - Planes de acción.
=> fix: corrección bug formulación - Planes de acción.

src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts
Solucion de conflictos en pages-routing y pages.module entre 'fixedEdisson/notificaciones' y 'feature/tabla_pendientes'
=> fix: solucion de conflictos en pages-routing y pages.module

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.scss, src/app/pages/evaluacion/evaluacion.component.ts
=> feat: ajuste y modificacion de la logica y coloriado de campos de brecha

src/app/pages/pendientes/pendientes-seguimiento/tabla-pendientes-seguimiento.component.html, src/app/pages/pendientes/pendientes-seguimiento/tabla-pendientes-seguimiento.component.scss, src/app/pages/pendientes/pendientes-seguimiento/tabla-pendientes-seguimiento.component.ts
#911 
Se implementó todo la funcionalidad correspondiente a la selección de planes para su posterior verificación, además, de tener en cuenta cada una de sus actividades internas para validar si la verificación del plan/proyecto es posible o no.
=> feat: planes pendientes en seguimiento seleccionables para verificar

src/app/pages/plan/construir-plan/construir-plan.component.ts
#877 
- Ajuste lógica de componentes en el cliente asociados a la modificación de plantillas de planes de acción en formulación
=> feat: Consumo controlador actualización planes

src/app/pages/pendientes/pendientes-seguimiento/tabla-pendientes-seguimiento.component.ts
=> feat: periodos en popup de error

src/app/pages/directives/resize.directive.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.scss, src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
Solución al issue #904
Observaciones en la issue(revisar)
=> feat: autoresize en textarea's de seguimiento

src/app/pages/banco-de-proyectos/proyectos-inversion-macro/magnitudes-presupuesto/magnitudes-presupuesto.component.ts, src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.scss, src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/recursos/recursos.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts
#927
- Refinamiento del campo Brecha y asignación de colores para el campo Cumplimiento por meta
=> feat: Refinamiento campo Brecha

src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/plan/gestion-usuarios/gestion-usuarios.component.html, src/app/pages/plan/gestion-usuarios/gestion-usuarios.component.scss, src/app/pages/plan/gestion-usuarios/gestion-usuarios.component.spec.ts, src/app/pages/plan/gestion-usuarios/gestion-usuarios.component.ts, src/app/pages/plan/gestion-usuarios/utils/gestion-usuarios.models.ts
#873 #912 
- Se agregó el componente visual en Angular asociado a la consulta y visualización de usuarios por roles/correo electrónico.
- Los datos de la búsqueda (en caso de que haya) se muestran en una tabla, de lo contrario se muestra un Swal indicando que no hay registros asociados a los parámetros de búsqueda.
- Se agregó el botón de limpiar formulario.
- Se agregaron validaciones para los dos campos del formulario.
- Se ajustó el tamaño de la tabla y se quitó la validación de seleccionar el **Rol** como parámetro obligatorio para buscar usuarios por rol.
=> feat: se agregó el componente de visualización de usuarios/roles

src/app/pages/evaluacion/evaluacion.component.html, src/app/pages/evaluacion/evaluacion.component.ts, src/app/pages/evaluacion/resumen/resumen.component.html, src/app/pages/evaluacion/resumen/resumen.component.ts
Se agrega el filtro por trimestre con las respectivas validaciones y activaciones de componentes
Dentro de el mismo, también se soluciona un pequeño error al actualizar los select de plan y vigencia
#964
=> feat: evaluacion filtro periodo

src/app/pages/formulacion/formulacion.component.ts
- udistrital/planeacion_cliente/issues/1044
Ajuste en priorización de los planes que tienen verificación con fechas
=> fix: planes repetidos

src/app/pages/formulacion/formulacion.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1069 - Falta probar.
=> Feat:Ajuste para ocultar las vinculaciones antiguar 

src/app/@core/services/codigos.service.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/identificacion-actividades-recursos/identificacion-actividades-recursos.component.ts, src/app/pages/banco-de-proyectos/proyectos-inversion-macro/proyectos-de-inversion-vigentes/proyectos-de-inversion-vigentes.component.ts, src/app/pages/formulacion/contratistas/contratistas.component.ts, src/app/pages/formulacion/docentes/docentes.component.ts, src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/recursos.component.ts, src/app/pages/ped/ped.component.ts, src/app/pages/pendientes/pendientes-formulacion/tabla-pendientes-formulacion.component.ts, src/app/pages/pendientes/pendientes-seguimiento/tabla-pendientes-seguimiento.component.ts, src/app/pages/plan-indicativo/consultar-pi/consultar-pi.component.ts, src/app/pages/plan/arbol/arbol.component.ts, src/app/pages/plan/construir-plan-proyecto/construir-plan-proyecto.component.ts, src/app/pages/plan/construir-plan/construir-plan.component.ts, src/app/pages/plan/crear-plan/crear-plan.component.ts, src/app/pages/plan/habilitar-reporte/funcionamiento/funcionamiento.component.ts, src/app/pages/plan/habilitar-reporte/inversion/inversion.component.ts, src/app/pages/plan/listar-plan/listar-plan.component.ts, src/app/pages/pui/pui.component.ts, src/app/pages/reportes/reporte-plan-anual/plan-anual.component.ts, src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
- https://github.com/udistrital/planeacion_cliente/issues/1103
=> feat: optimización codigos de identificación

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.html, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1063
=> feat:adicion Campo id actividad(seguimiento)

src/app/pages/formulacion/formulacion.component.html, src/app/pages/formulacion/formulacion.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1078 
Ajuste de los botones cuando se accede a una actividad de un plan en fase de formulación que su estado ya esta avalado.
=> feat:ajuste botones en la revision de una actividad en formulacion 

src/app/pages/pages.module.ts
- https://github.com/udistrital/planeacion_cliente/issues/1151
=> fix: se agrega el GestorDocumentalService en pages.module

src/app/pages/evaluacion/evaluacion-plan/evaluacion-plan.component.html, src/app/pages/evaluacion/evaluacion-plan/evaluacion-plan.component.ts
github.com/udistrital/planeacion_cliente/issues/1151
=> fix:ajuste del grafico circular de evaluacion por trimestre 

src/app/pages/evaluacion/evaluacion-plan/evaluacion-plan.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1151
=> feat:ajuste grafico de la grafica circular 

src/app/pages/evaluacion/evaluacion-plan/evaluacion-plan.component.html, src/app/pages/evaluacion/evaluacion-plan/evaluacion-plan.component.ts, src/environments/environment.ts
- https://github.com/udistrital/planeacion_cliente/issues/1151
=> feat: cambio valores vacios

src/app/pages/evaluacion/evaluacion-plan/evaluacion-plan.component.html, src/app/pages/evaluacion/evaluacion-plan/evaluacion-plan.component.ts
- https://github.com/udistrital/planeacion_cliente/issues/1151
=> feat: agregar colores en la gráfica de barras de evaluación 

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts, src/app/pages/seguimiento/gestion-seguimiento/gestion-seguimiento.component.ts
/ https://github.com/udistrital/planeacion_cliente/issues/1063
=> feat: limpieza de codigo basura 

src/app/pages/plan-accion/plan-accion-formulacion/plan-accion-formulacion.component.ts, src/app/pages/plan-accion/plan-accion-seguimiento/plan-accion-seguimiento.component.ts
- Se aumenta el tiempo de espera a 5 segundos y se borra el async.
=> fix: Se aumenta el tiempo de espera a 5 segundos y se borra el async.

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1140
=> correccion divion 0/0 solo cuando denominador es variable 

src/app/pages/pendientes/pendientes-seguimiento/tabla-pendientes-seguimiento.component.ts, src/app/pages/plan-accion/plan-accion-seguimiento/plan-accion-seguimiento.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1151
=> fix: ajuste de pendientes y consulta

src/app/pages/formulacion/formulacion.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1069 : Ajuste a la vinculación mas reciente.
=> fix: vinculacion mas reciente en fase de formulacion

src/app/pages/formulacion/formulacion.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1069
=> fix: vinculacion mas reciente en fase de formulacion v4

src/app/pages/formulacion/formulacion.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1069
=> Fix/vinculacion mas reciente 

src/app/pages/formulacion/formulacion.component.ts, src/app/pages/formulacion/recursos/rubros.ts
=> feat: update_rubros

src/app/pages/seguimiento/generar-trimestre/generar-trimestre.component.ts
- https://github.com/udistrital/planeacion_cliente/issues/1134
=> feat: simplificación de la lógica en los indicadores de seguimiento

src/app/pages/plan-accion/plan-accion-seguimiento/plan-accion-seguimiento.component.ts
https://github.com/udistrital/planeacion_cliente/issues/1224
=> fix: descarga planes filtro

package-lock.json, package.json
Reverts udistrital/planeacion_cliente#1245
=> Revert "build(deps): bump braces and @angular-devkit/build-angular"

src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts
/ https://github.com/udistrital/planeacion_cliente/issues/1255
=> ajustes finales(eliminar adicion) 

src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.html, src/app/pages/plan/construir-plan/agregar-dialog/agregar-dialog.component.ts, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.html, src/app/pages/plan/construir-plan/editar-dialog/editar-dialog.component.ts
/ https://github.com/udistrital/planeacion_cliente/issues/1255
=> feat:visual componente adicionar

src/app/pages/plan-accion/plan-accion-seguimiento/plan-accion-seguimiento.component.ts
fix/Cannot read properties of null (for each)
=> fix/Cannot read properties of null (for each)

src/app/pages/pendientes/pendientes-formulacion/tabla-pendientes-formulacion.component.ts
fix/Update tabla-pendientes-formulacion.component.ts
=> fix/Update tabla-pendientes-formulacion.component.ts

src/app/pages/seguimiento/listar-plan-accion-anual/seguimiento.component.ts
Cerrar el modal por si hay error
=> fix: cerrar el modal por si hay error
